// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(CooklangFindFFI)
    import CooklangFindFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cooklang_find_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cooklang_find_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/**
 * FFI-safe representation of a recipe entry.
 *
 * This is the main type for representing recipes across the FFI boundary.
 */
public protocol FfiRecipeEntryProtocol: AnyObject {
    /**
     * Returns the full content of the recipe.
     */
    func content() throws -> String

    /**
     * Returns the file name if this recipe is backed by a file.
     */
    func fileName() -> String?

    /**
     * Gets a specific metadata value by key as a JSON string.
     */
    func getMetadataValue(key: String) -> String?

    /**
     * Gets a step image by section and step number.
     *
     * For linear recipes (no sections), use section = 0.
     * Steps are one-indexed (first step is 1).
     */
    func getStepImage(section: UInt32, step: UInt32) -> String?

    /**
     * Returns true if this is a menu file (.menu) rather than a recipe (.cook).
     */
    func isMenu() -> Bool

    /**
     * Returns the recipe's metadata.
     */
    func metadata() -> FfiMetadata

    /**
     * Returns the name of the recipe.
     */
    func name() -> String?

    /**
     * Returns the file path if this recipe is backed by a file.
     */
    func path() -> String?

    /**
     * Returns all step images for the recipe.
     */
    func stepImages() -> FfiStepImages

    /**
     * Returns the recipe's tags.
     */
    func tags() -> [String]

    /**
     * Returns the URL or path to the recipe's title image.
     */
    func titleImage() -> String?
}

/**
 * FFI-safe representation of a recipe entry.
 *
 * This is the main type for representing recipes across the FFI boundary.
 */
open class FfiRecipeEntry:
    FfiRecipeEntryProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_cooklang_find_fn_clone_ffirecipeentry(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_cooklang_find_fn_free_ffirecipeentry(pointer, $0) }
    }

    /**
     * Returns the full content of the recipe.
     */
    open func content() throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
            uniffi_cooklang_find_fn_method_ffirecipeentry_content(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the file name if this recipe is backed by a file.
     */
    open func fileName() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_file_name(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Gets a specific metadata value by key as a JSON string.
     */
    open func getMetadataValue(key: String) -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_get_metadata_value(self.uniffiClonePointer(),
                                                                             FfiConverterString.lower(key), $0)
        })
    }

    /**
     * Gets a step image by section and step number.
     *
     * For linear recipes (no sections), use section = 0.
     * Steps are one-indexed (first step is 1).
     */
    open func getStepImage(section: UInt32, step: UInt32) -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_get_step_image(self.uniffiClonePointer(),
                                                                         FfiConverterUInt32.lower(section),
                                                                         FfiConverterUInt32.lower(step), $0)
        })
    }

    /**
     * Returns true if this is a menu file (.menu) rather than a recipe (.cook).
     */
    open func isMenu() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_is_menu(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the recipe's metadata.
     */
    open func metadata() -> FfiMetadata {
        return try! FfiConverterTypeFfiMetadata.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_metadata(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the name of the recipe.
     */
    open func name() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_name(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the file path if this recipe is backed by a file.
     */
    open func path() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_path(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns all step images for the recipe.
     */
    open func stepImages() -> FfiStepImages {
        return try! FfiConverterTypeFfiStepImages.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_step_images(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the recipe's tags.
     */
    open func tags() -> [String] {
        return try! FfiConverterSequenceString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_tags(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the URL or path to the recipe's title image.
     */
    open func titleImage() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipeentry_title_image(self.uniffiClonePointer(), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRecipeEntry: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiRecipeEntry

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiRecipeEntry {
        return FfiRecipeEntry(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiRecipeEntry) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRecipeEntry {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiRecipeEntry, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecipeEntry_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiRecipeEntry {
    return try FfiConverterTypeFfiRecipeEntry.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecipeEntry_lower(_ value: FfiRecipeEntry) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiRecipeEntry.lower(value)
}

/**
 * FFI-safe representation of a recipe tree.
 */
public protocol FfiRecipeTreeProtocol: AnyObject {
    /**
     * Returns all nodes in the tree as a flat list.
     */
    func allNodes() -> [FfiTreeNode]

    /**
     * Returns all recipes in the tree.
     */
    func allRecipes() -> [FfiRecipeEntry]

    /**
     * Gets a child node by name from the root.
     */
    func getChild(name: String) -> FfiTreeNode?

    /**
     * Gets a recipe by path components (e.g., ["breakfast", "pancakes"]).
     */
    func getRecipeAtPath(path: [String]) -> FfiRecipeEntry?

    /**
     * Gets the recipe at the root level if present.
     */
    func recipe() -> FfiRecipeEntry?

    /**
     * Returns the root node information.
     */
    func root() -> FfiTreeNode
}

/**
 * FFI-safe representation of a recipe tree.
 */
open class FfiRecipeTree:
    FfiRecipeTreeProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_cooklang_find_fn_clone_ffirecipetree(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_cooklang_find_fn_free_ffirecipetree(pointer, $0) }
    }

    /**
     * Returns all nodes in the tree as a flat list.
     */
    open func allNodes() -> [FfiTreeNode] {
        return try! FfiConverterSequenceTypeFfiTreeNode.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_all_nodes(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns all recipes in the tree.
     */
    open func allRecipes() -> [FfiRecipeEntry] {
        return try! FfiConverterSequenceTypeFfiRecipeEntry.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_all_recipes(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Gets a child node by name from the root.
     */
    open func getChild(name: String) -> FfiTreeNode? {
        return try! FfiConverterOptionTypeFfiTreeNode.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_get_child(self.uniffiClonePointer(),
                                                                   FfiConverterString.lower(name), $0)
        })
    }

    /**
     * Gets a recipe by path components (e.g., ["breakfast", "pancakes"]).
     */
    open func getRecipeAtPath(path: [String]) -> FfiRecipeEntry? {
        return try! FfiConverterOptionTypeFfiRecipeEntry.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_get_recipe_at_path(self.uniffiClonePointer(),
                                                                            FfiConverterSequenceString.lower(path), $0)
        })
    }

    /**
     * Gets the recipe at the root level if present.
     */
    open func recipe() -> FfiRecipeEntry? {
        return try! FfiConverterOptionTypeFfiRecipeEntry.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_recipe(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Returns the root node information.
     */
    open func root() -> FfiTreeNode {
        return try! FfiConverterTypeFfiTreeNode.lift(try! rustCall {
            uniffi_cooklang_find_fn_method_ffirecipetree_root(self.uniffiClonePointer(), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRecipeTree: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiRecipeTree

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiRecipeTree {
        return FfiRecipeTree(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiRecipeTree) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRecipeTree {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiRecipeTree, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecipeTree_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiRecipeTree {
    return try FfiConverterTypeFfiRecipeTree.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRecipeTree_lower(_ value: FfiRecipeTree) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiRecipeTree.lower(value)
}

/**
 * FFI-safe representation of recipe metadata.
 */
public struct FfiMetadata {
    /**
     * Recipe title if present
     */
    public let title: String?
    /**
     * Number of servings if present
     */
    public let servings: Int64?
    /**
     * List of tags
     */
    public let tags: [String]
    /**
     * Primary image URL if present
     */
    public let imageUrl: String?
    /**
     * All metadata as JSON string for complex access
     */
    public let rawJson: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Recipe title if present
         */ title: String?,
        /* 
            * Number of servings if present
            */ servings: Int64?,
        /* 
            * List of tags
            */ tags: [String],
        /* 
            * Primary image URL if present
            */ imageUrl: String?,
        /* 
            * All metadata as JSON string for complex access
            */ rawJson: String
    ) {
        self.title = title
        self.servings = servings
        self.tags = tags
        self.imageUrl = imageUrl
        self.rawJson = rawJson
    }
}

extension FfiMetadata: Equatable, Hashable {
    public static func == (lhs: FfiMetadata, rhs: FfiMetadata) -> Bool {
        if lhs.title != rhs.title {
            return false
        }
        if lhs.servings != rhs.servings {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.imageUrl != rhs.imageUrl {
            return false
        }
        if lhs.rawJson != rhs.rawJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(title)
        hasher.combine(servings)
        hasher.combine(tags)
        hasher.combine(imageUrl)
        hasher.combine(rawJson)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMetadata {
        return
            try FfiMetadata(
                title: FfiConverterOptionString.read(from: &buf),
                servings: FfiConverterOptionInt64.read(from: &buf),
                tags: FfiConverterSequenceString.read(from: &buf),
                imageUrl: FfiConverterOptionString.read(from: &buf),
                rawJson: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: FfiMetadata, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterOptionInt64.write(value.servings, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionString.write(value.imageUrl, into: &buf)
        FfiConverterString.write(value.rawJson, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMetadata_lift(_ buf: RustBuffer) throws -> FfiMetadata {
    return try FfiConverterTypeFfiMetadata.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMetadata_lower(_ value: FfiMetadata) -> RustBuffer {
    return FfiConverterTypeFfiMetadata.lower(value)
}

/**
 * FFI-safe representation of step images.
 */
public struct FfiStepImages {
    /**
     * List of all step images
     */
    public let images: [StepImageEntry]
    /**
     * Total count of images
     */
    public let count: UInt32

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * List of all step images
         */ images: [StepImageEntry],
        /* 
            * Total count of images
            */ count: UInt32
    ) {
        self.images = images
        self.count = count
    }
}

extension FfiStepImages: Equatable, Hashable {
    public static func == (lhs: FfiStepImages, rhs: FfiStepImages) -> Bool {
        if lhs.images != rhs.images {
            return false
        }
        if lhs.count != rhs.count {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(images)
        hasher.combine(count)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStepImages: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStepImages {
        return
            try FfiStepImages(
                images: FfiConverterSequenceTypeStepImageEntry.read(from: &buf),
                count: FfiConverterUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: FfiStepImages, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeStepImageEntry.write(value.images, into: &buf)
        FfiConverterUInt32.write(value.count, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStepImages_lift(_ buf: RustBuffer) throws -> FfiStepImages {
    return try FfiConverterTypeFfiStepImages.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStepImages_lower(_ value: FfiStepImages) -> RustBuffer {
    return FfiConverterTypeFfiStepImages.lower(value)
}

/**
 * FFI-safe representation of a tree node.
 */
public struct FfiTreeNode {
    /**
     * Name of the node (directory or recipe name)
     */
    public let name: String
    /**
     * Full path to this node
     */
    public let path: String
    /**
     * True if this node has a recipe
     */
    public let hasRecipe: Bool
    /**
     * Names of child nodes
     */
    public let children: [String]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Name of the node (directory or recipe name)
         */ name: String,
        /* 
            * Full path to this node
            */ path: String,
        /* 
            * True if this node has a recipe
            */ hasRecipe: Bool,
        /* 
            * Names of child nodes
            */ children: [String]
    ) {
        self.name = name
        self.path = path
        self.hasRecipe = hasRecipe
        self.children = children
    }
}

extension FfiTreeNode: Equatable, Hashable {
    public static func == (lhs: FfiTreeNode, rhs: FfiTreeNode) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.hasRecipe != rhs.hasRecipe {
            return false
        }
        if lhs.children != rhs.children {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(path)
        hasher.combine(hasRecipe)
        hasher.combine(children)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTreeNode: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTreeNode {
        return
            try FfiTreeNode(
                name: FfiConverterString.read(from: &buf),
                path: FfiConverterString.read(from: &buf),
                hasRecipe: FfiConverterBool.read(from: &buf),
                children: FfiConverterSequenceString.read(from: &buf)
            )
    }

    public static func write(_ value: FfiTreeNode, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterBool.write(value.hasRecipe, into: &buf)
        FfiConverterSequenceString.write(value.children, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTreeNode_lift(_ buf: RustBuffer) throws -> FfiTreeNode {
    return try FfiConverterTypeFfiTreeNode.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTreeNode_lower(_ value: FfiTreeNode) -> RustBuffer {
    return FfiConverterTypeFfiTreeNode.lower(value)
}

/**
 * A key-value pair for metadata entries.
 */
public struct MetadataEntry {
    public let key: String
    public let value: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }
}

extension MetadataEntry: Equatable, Hashable {
    public static func == (lhs: MetadataEntry, rhs: MetadataEntry) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(value)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMetadataEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MetadataEntry {
        return
            try MetadataEntry(
                key: FfiConverterString.read(from: &buf),
                value: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: MetadataEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMetadataEntry_lift(_ buf: RustBuffer) throws -> MetadataEntry {
    return try FfiConverterTypeMetadataEntry.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMetadataEntry_lower(_ value: MetadataEntry) -> RustBuffer {
    return FfiConverterTypeMetadataEntry.lower(value)
}

/**
 * A step image entry mapping section and step to an image path.
 */
public struct StepImageEntry {
    /**
     * Section number (0 for linear recipes, 1+ for sectioned recipes)
     */
    public let section: UInt32
    /**
     * Step number (1-indexed)
     */
    public let step: UInt32
    /**
     * Path to the image
     */
    public let imagePath: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Section number (0 for linear recipes, 1+ for sectioned recipes)
         */ section: UInt32,
        /* 
            * Step number (1-indexed)
            */ step: UInt32,
        /* 
            * Path to the image
            */ imagePath: String
    ) {
        self.section = section
        self.step = step
        self.imagePath = imagePath
    }
}

extension StepImageEntry: Equatable, Hashable {
    public static func == (lhs: StepImageEntry, rhs: StepImageEntry) -> Bool {
        if lhs.section != rhs.section {
            return false
        }
        if lhs.step != rhs.step {
            return false
        }
        if lhs.imagePath != rhs.imagePath {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(section)
        hasher.combine(step)
        hasher.combine(imagePath)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeStepImageEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StepImageEntry {
        return
            try StepImageEntry(
                section: FfiConverterUInt32.read(from: &buf),
                step: FfiConverterUInt32.read(from: &buf),
                imagePath: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: StepImageEntry, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.section, into: &buf)
        FfiConverterUInt32.write(value.step, into: &buf)
        FfiConverterString.write(value.imagePath, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStepImageEntry_lift(_ buf: RustBuffer) throws -> StepImageEntry {
    return try FfiConverterTypeStepImageEntry.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStepImageEntry_lower(_ value: StepImageEntry) -> RustBuffer {
    return FfiConverterTypeStepImageEntry.lower(value)
}

/**
 * FFI-safe error type that wraps all possible errors.
 */
public enum CooklangError {
    case NotFound(message: String)
    case IoError(message: String)
    case ParseError(message: String)
    case InvalidPath(message: String)
    case SearchError(message: String)
    case TreeError(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCooklangError: FfiConverterRustBuffer {
    typealias SwiftType = CooklangError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CooklangError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .NotFound(
                message: FfiConverterString.read(from: &buf)
            )
        case 2: return try .IoError(
                message: FfiConverterString.read(from: &buf)
            )
        case 3: return try .ParseError(
                message: FfiConverterString.read(from: &buf)
            )
        case 4: return try .InvalidPath(
                message: FfiConverterString.read(from: &buf)
            )
        case 5: return try .SearchError(
                message: FfiConverterString.read(from: &buf)
            )
        case 6: return try .TreeError(
                message: FfiConverterString.read(from: &buf)
            )
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CooklangError, into buf: inout [UInt8]) {
        switch value {
        case let .NotFound(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)

        case let .IoError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)

        case let .ParseError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)

        case let .InvalidPath(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)

        case let .SearchError(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)

        case let .TreeError(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
        }
    }
}

extension CooklangError: Equatable, Hashable {}

extension CooklangError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeFfiRecipeEntry: FfiConverterRustBuffer {
    typealias SwiftType = FfiRecipeEntry?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiRecipeEntry.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiRecipeEntry.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeFfiTreeNode: FfiConverterRustBuffer {
    typealias SwiftType = FfiTreeNode?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiTreeNode.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiTreeNode.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiRecipeEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRecipeEntry]

    static func write(_ value: [FfiRecipeEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRecipeEntry.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRecipeEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRecipeEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiRecipeEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiTreeNode: FfiConverterRustBuffer {
    typealias SwiftType = [FfiTreeNode]

    static func write(_ value: [FfiTreeNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiTreeNode.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiTreeNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiTreeNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiTreeNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeStepImageEntry: FfiConverterRustBuffer {
    typealias SwiftType = [StepImageEntry]

    static func write(_ value: [StepImageEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStepImageEntry.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [StepImageEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [StepImageEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeStepImageEntry.read(from: &buf))
        }
        return seq
    }
}

/**
 * Builds a hierarchical tree of all recipes in a directory.
 *
 * Recursively scans the directory for .cook and .menu files,
 * organizing them into a tree structure mirroring the filesystem.
 *
 * # Arguments
 * * `base_dir` - Root directory to build the tree from
 *
 * # Returns
 * The recipe tree, or an error.
 */
public func buildTree(baseDir: String) throws -> FfiRecipeTree {
    return try FfiConverterTypeFfiRecipeTree.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
        uniffi_cooklang_find_fn_func_build_tree(
            FfiConverterString.lower(baseDir), $0
        )
    })
}

/**
 * Loads a recipe by name from the specified directories.
 *
 * Searches through the provided directories in order for a recipe file
 * matching the given name. Automatically handles .cook and .menu extensions.
 *
 * # Arguments
 * * `base_dirs` - List of directory paths to search
 * * `name` - Recipe name to search for (with or without extension)
 *
 * # Returns
 * The recipe if found, or an error.
 */
public func getRecipe(baseDirs: [String], name: String) throws -> FfiRecipeEntry {
    return try FfiConverterTypeFfiRecipeEntry.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
        uniffi_cooklang_find_fn_func_get_recipe(
            FfiConverterSequenceString.lower(baseDirs),
            FfiConverterString.lower(name), $0
        )
    })
}

/**
 * Returns the library version.
 */
public func libraryVersion() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_cooklang_find_fn_func_library_version($0)
    })
}

/**
 * Creates a recipe from file content.
 *
 * Useful for creating recipes from sources other than files,
 * such as network responses or programmatically generated content.
 *
 * # Arguments
 * * `content` - The full recipe content including any YAML frontmatter
 * * `name` - Optional name for the recipe
 *
 * # Returns
 * The recipe entry, or an error if parsing fails.
 */
public func recipeFromContent(content: String, name: String?) throws -> FfiRecipeEntry {
    return try FfiConverterTypeFfiRecipeEntry.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
        uniffi_cooklang_find_fn_func_recipe_from_content(
            FfiConverterString.lower(content),
            FfiConverterOptionString.lower(name), $0
        )
    })
}

/**
 * Creates a recipe from a file path.
 *
 * # Arguments
 * * `path` - The path to the recipe file
 *
 * # Returns
 * The recipe entry, or an error if loading fails.
 */
public func recipeFromPath(path: String) throws -> FfiRecipeEntry {
    return try FfiConverterTypeFfiRecipeEntry.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
        uniffi_cooklang_find_fn_func_recipe_from_path(
            FfiConverterString.lower(path), $0
        )
    })
}

/**
 * Searches for recipes matching a query string.
 *
 * Performs full-text search across recipe filenames and contents
 * in the specified directory and subdirectories.
 *
 * # Arguments
 * * `base_dir` - Root directory to search in
 * * `query` - Search query (can contain multiple space-separated terms)
 *
 * # Returns
 * List of matching recipes sorted by relevance.
 */
public func search(baseDir: String, query: String) throws -> [FfiRecipeEntry] {
    return try FfiConverterSequenceTypeFfiRecipeEntry.lift(rustCallWithError(FfiConverterTypeCooklangError.lift) {
        uniffi_cooklang_find_fn_func_search(
            FfiConverterString.lower(baseDir),
            FfiConverterString.lower(query), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cooklang_find_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_cooklang_find_checksum_func_build_tree() != 33096 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_func_get_recipe() != 1817 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_func_library_version() != 55411 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_func_recipe_from_content() != 23295 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_func_recipe_from_path() != 40862 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_func_search() != 59640 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_content() != 46621 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_file_name() != 167 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_get_metadata_value() != 31132 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_get_step_image() != 39989 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_is_menu() != 26536 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_metadata() != 18424 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_name() != 12431 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_path() != 52704 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_step_images() != 59649 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_tags() != 60238 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipeentry_title_image() != 17074 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_all_nodes() != 53124 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_all_recipes() != 27491 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_get_child() != 20134 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_get_recipe_at_path() != 8996 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_recipe() != 1902 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_cooklang_find_checksum_method_ffirecipetree_root() != 14587 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
